[general]
# Exit directly after copy / save action.
early-exit = true

# Ensure clipboard contents persist after satty closes.
copy-command = "wl-copy"

# Select the tool on startup:
#   pointer, crop, line, arrow, rectangle, text, marker, blur, brush
initial-tool = "brush"
